name: Build and test documentation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install pdm
          pdm install

      - name: Build docs
        run: pdm run docs-prod
